# Generated by Django 3.2 on 2025-02-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20250225_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.review', verbose_name='Рейтинг'),
        ),
    ]
